openedx/edx-analytics-configuration

- batch/library/emr
- batch/provision.yml
This enables us to override *all* of the instance groups. This enables us to run clusters with large numbers of core instances acquired from the spot market.
Some of our jobs were failing on m3.xlarge clusters because they were running out of space in HDFS. This is due to the fact that m3.xlarge uses SSDs instead of spinning platter disks and have much less space available per node. For this reason we need more core nodes and less task nodes.
@brianhw
> Allow for more flexible instance group configurations

- .gitignore
- batch/library/emr
- requirements.txt
@brianhw @jab5569 
This change sets a default service role for new EMR clusters. Hopefully this will allow us to continue to provision clusters after the June 30th deadline.
> add support for service roles

- batch/library/emr
- batch/provision.yml
- batch/terminate.yml
This commit adds ability to provision EMR clusters in regions other than the default `us-east-1` region. The provision and terminate scripts now accept an optional `role` parameter, which defaults to `'eu-east-1'`.
*Partner Information*: not an edX partner - 3rd party-hosted open edX instance
*JIRA Ticket*: https://openedx.atlassian.net/browse/OSPR-675
> Add ability to specify AWS region.

- roles/user/tasks/main.yml
The "copy additional authorized keys" task fails to run because the `mode` parameter is specified twice. This commit removes the second `mode` parameter.
*Partner Information*: not an edX partner - 3rd party-hosted open edX instance
*JIRA Ticket*: https://openedx.atlassian.net/browse/OSPR-676
> Remove redundant 'mode' argument.

- batch/terminate.yml
It is convenient for us to have a default value here so that the region is not a required parameter to this playbook.
@jab5569 @jrowan
> set a default region for terminate

- batch/library/emr
- batch/provision.yml
- requirements.txt
- roles/user/tasks/main.yml
No longer uses any older boto code, which is being deprecated now that boto3 is released.
Provides support for release_label (4.x) format in addition to extending ami_version (2.x, 3.x) format.
Still supports hive_install and pig_install steps for 3.x, and supports applications for 3.x (spark) and 4.x (all apps including Hive, Pig, Spark).
@mulby @jab5569
> Port EMR deployment to use boto3.

- batch/library/emr
EMR may fail to provision a master instance on the first try.  So calling list-instances with an instance-group-type of 'MASTER' may indeed return more than one instance.  The failed instances have a State of "TERMINATED"  with code "INSTANCE_FAILURE".   Rather than checking all of these, we just assume instead that the "good" master is the one at the end of the list.
@mulby
> Handle transient failures in provisioning master instance.

- batch/sample-emr-vars.yml
`TERMINATE_JOB_FLOW` is the default behavior. This is mostly for documentation purposes to make it easier to see how/where to set a different action on failure.
JIRA ticket: https://openedx.atlassian.net/browse/OLIVE-25
> Set action_on_failure in sample-emr-vars.yml.

- batch/bootstrap/security.sh
@e0d @brianhw 
Open source community members have asked me how we fixed this issue, I'd like to share this script with them. Note this is somewhat useless without the actual *.deb files.
Also note that the bucket name was already public information.
> fix debian squeeze repo issue

- automation/run-automated-task.sh
Currently the `run-automated-task.sh` script passes the `--branch` parameter to `remote-task`, but there is no way to pass the `--repo` parameter.
This change lets you set the `--repo` parameter via `TASKS_REPO` environment variable, allowing you to use your own fork of edx-analytics-pipeline.
JIRA ticket: https://openedx.atlassian.net/browse/OLIVE-25
> Pass --repo parameter to remote-task.

- Makefile
Allows edx-analytics-configuration to use ansible 1.4.4 to provision EMR from boxes
provisioned for use with jenkins analytics using edx/configuration ansible 1.9.3.
**JIRA tickets**: Cleanup for [OLIVE-22](https://openedx.atlassian.net/browse/OLIVE-20), [OC-1512](https://tasks.opencraft.com/browse/OC-1512)
**Discussions**: See [discussion on PR 15](https://github.com/edx-ops/edx-jenkins-job-dsl/pull/15#issuecomment-204265069).
**Dependencies**: None
**Sandbox URL**: 
http://52.20.136.133:8080/ - ping me for login credentials.
**Testing instructions**:
See [edx/configuration PR #2939](https://github.com/edx/configuration/pull/2939) for full test instructions.
Expected result is the EMR instance will provision and terminate successfully (if your configuration is correct).  The analytics …
> Allows ansible 1.4.4 to be run on boxes provisioned with ansible 1.9.3

- automation/run-automated-task.sh
Running virtualenv on an existing venv can cause some very weird issues. Specifically we've seen it overwrite existing installations of pip with whatever default it wants to use. This is problematic since we are upgrading pip to 7.1.2 and some older versions of virtualenv want to install 1.5.6. This causes conflicting pip installations to be installed alongside one another.
Reviewers:
> fix existing venv issue

- automation/run-automated-task.sh
- batch/library/emr
- batch/provision.yml
- plugins/ec2.py
Provides the following features:
1. Allow AWS region used by the dynamic inventory script (ec2.py) to be configured via an environment variable instead of the hardcoded value in ec2.ini
2. When using edx-analytics-pipeline to just run remote-task in run-automated-task.sh, use "make bootstrap" instead of "make install". This is *much* faster and only installs the minimum dependency set needed to run remote-task.
3. Support additional master security groups. We are taking the approach of using the default security groups for master nodes and creating a new one that allows SSH from jenkins. This feature had to be fixed to enable assigning additional security groups for master nodes.
Reviewers:
FYI: @mtyaka @pomegranited
Related PRs:
* https://github.com/edx/edx-analytics-pipeline/pull/237 - …
> Misc updates found during execution of new deployment

- automation/run-automated-task.sh
Passes `--virtualenv-extra-args` from environment variable.
Depends on https://github.com/edx/edx-analytics-pipeline/pull/239.
cf. [OLIVE-29](https://openedx.atlassian.net/browse/OLIVE-29)
> Pass --virtualenv-extra-args to remote-task.

- automation/run-automated-task.sh
Some analytics pipelines use an override config file instead of secure config file in a secure repo.
This change modifies `run-automated-tasks.sh`'s `remote-task` call to allow the `--secure-*` arguments to be empty, and adds the optional `--override-config` argument.
Prior to this change, `run-automated-tasks.sh`'s `remote-task` call would error if there was no `SECURE_REPO`, `SECURE_BRANCH` and `SECURE_CONFIG` set, and not respond to any `OVERRIDE_CONFIG` env var.
**JIRA tickets**: [OC-1561](https://tasks.opencraft.com/browse/OC-1561)
**Testing instructions**:
1. Run `automation/run-automated-tasks.sh` on a configured analytics pipeline server, using these combinations of arguments:
* Unset `SECURE_REPO`, `SECURE_BRANCH`, `SECURE_CONFIG`, `OVERRIDE_CONFIG`
* Unset `SECURE_REPO`, …
> Allows --override-config to be used in place of --secure-*

- Makefile
We just need to specify which SSH username Ansible should be using to connect to the EMR master node when collecting metrics.
> Set the right SSH username to use when collecting metrics.

- Makefile
- batch/collect.yml
As we're still seeing some weird SSH issues when connecting to the master node, we're now using `-vvvv` so we can get the full SSH output as we try to debug these problems.
We're also invoking the playbook by appending `|| true`, so that these SSH failures don't cause Jenkins to think the job failed.  This is important because some tasks downstream will not run if their upstream
requirement "failed" because of an SSH error when collecting the metrics.
We're also spitting out the stdout from the collection script to console so that we have a better idea of what the script is doing, just in case that's part of the "SSH error."
> Add some debugging to metrics collection, which is still tumultuous.

- automation/run-automated-task.sh
Some of the workflow jobs generate a lot of log output, and when we're trying to see if metrics were collected, etc, that stuff is buried somewhere in the middle of the "console output" for the job.
We're just moving the metrics collection to the very end so that it's easier to find no matter how large the workflow's log output is.
> Read the workflow logs before collecting metrics.

- batch/library/emr
- requirements.txt
This change the EBS volume size to be configured using a new `volume_size` configuration parameter.
Example `instance_groups` configuration which sets `volume_size` on the `core` instance:
```yaml
instance_groups:
master:
num_instances: 1
type: m4.medium
market: ON_DEMAND
core:
num_instances: 1
type: m4.large
market: ON_DEMAND
volume_size: 64
task:
num_instances: 2
type: m4.large
market: ON_DEMAND
```
**Author notes and concerns**:
1. The current version of boto3 (1.1.0) does not support this option. The latest version (1.4.4) does.
1. I'm unsure how to provide test instructions.  Our client deployed their cluster using this change, and this made the volume size increase as specified.
1. Do you need an additional OpenCraft reviewer here?  Or any further testing done?
**Reviewers**
> Adds EbsConfiguration stanza to InstanceGroup specification

- batch/library/emr
- batch/provision.yml
Launching EMR clusters based on instance fleet specifications allows us to specify a set of subnets, and a set of instance types, and opportunistically launch clusters in the best priced subnet with the best mix of instance types to meet the capacity demands.
> [DE-276] Support for launching EMR clusters based on instance fleets.

- ansible.cfg
- batch/library/emr
- batch/provision.yml
Since we define our var overrides via extra vars with a dictionary,
Ansible's default behaviour is to wholesale swap the dictionaries,
seemingly.  This causes an issue when you try to use one or the other of
groups vs fleets.  Due to the logic we have to figure out if the user is
requesting an instance group-backed vs instance fleet-backed cluster, we
would potentially launch with a default group-based setup (ignoring the
fleet config) or with an erroneous string for the fleet config.
Basically, it's broken either way since we can't run 99% of our jobs on
an m1.medium.  From a technical standpoint, though, the cluster could
successfully launch and schedule Hadoop jobs.  They would just
inevitably fail from OOM at some point.
This change properly brings instance_fleets back into the fold …
> Change Ansible to merge in extra vars rather than replace.

- Makefile
- batch/library/emr
- batch/provision.yml
Due to how we use/used Ansible, the first iteration of instance fleet
support was being hampered by the default behaviours of Ansible, and by
some of the esoteric syntax we were using.
We slightly changed our logic for detecting fleet vs group, which allows
us to use a more crude-but-effective default value for this work.
> Allow instance group/instance fleet configuration to peacefully coexist.

- Makefile
Jenkins is running with ancient versions of pip and setuptools in its mkvirtualenv.  This upgrades the versions of each that jobs are run with.
> Upgrade pip and setuptools.

- batch/library/emr
This would allow us to use same EXTRA_VARS(for cluster provisioning playbook) for all seeded job by JOB DSL. We would be able to  provision a master only cluster by specifying 0 as spot_capacity on any Jenkins jobs.
> Skip setting core instance fleet spec if capacity is zero.

- ansible.cfg
This PR fixes issue with update-users jenkins job on new jenkins server which failed due to long ssh control path. I have tested user-activity-edge workflow using this branch which finished successfully.
> Shorten ssh control path

- automation/run-automated-task.sh
Identified as a pain point by the Excessive Alarm Reduction (EAR) working group: https://openedx.atlassian.net/wiki/spaces/DE/pages/996803190/Excessive+Alarm+reduction+working+group
> Do not fail pipeline jobs if make `collect.metrics` fails

- roles/user/tasks/main.yml
You might *think* these retries are un-needed - and so did I until failures actually happened twice this week - such as this one (shown below):
http://jenkins.analytics.edx.org/job/load-google-analytics-permissions/295/console
```
09:53:54 failed: [10.5.0.194] (item={u'github': True, u'type': u'admin', u'name': u'doctoryes'}) => {"changed": false, "dest": "/home/doctoryes/.ssh/authorized_keys", "item": {"github": true, "name": "doctoryes", "type": "admin"}, "msg": "Request failed", "response": "HTTP Error 500: Internal Server Error", "state": "absent", "status_code": 500, "url": "https://github.com/doctoryes.keys"}
```
> Add retry attempts to github pub key downloads.

- batch/provision.yml
Stopgap to retry more, in response to  increase in "instance fleet time out" errors on EMR.
> chore: Increase provision retries from 3 to 6.

- infrastructure/users.yml
Update the `$hosts` variable reference to `'{{ hosts }}'`
> Fix bug in hosts variable reference

- roles/user/tasks/main.yml
Update the `user` ansible role to both add and delete users depending on the value of `item.present`.
If `item.present` is not defined, that is interpreted as `item.present == True`.
> Let the user role both add and delete users based on the value of item.present
